set number
set cursorline

set background=dark
colorscheme hybrid

set guifont=Ricty\ Diminished\ Regular:h15

set lines=40
set columns=160

set expandtab
set tabstop=2
set shiftwidth=2

set nobackup
set noswapfile

let g:save_window_file = expand('~/.vimwinpos')
augroup SaveWindow
  autocmd!
  autocmd VimLeavePre * call s:save_window()
  function! s:save_window()
    let options = [
      \ 'set columns=' . &columns,
      \ 'set lines=' . &lines,
      \ 'winpos ' . getwinposx() . ' ' . getwinposy(),
      \ ]
    call writefile(options, g:save_window_file)
  endfunction
augroup END

if filereadable(g:save_window_file)
  execute 'source' g:save_window_file
endif
